# https://github.com/repository-settings/app
_extends: promise/.github

branches:
  - name: main
    protection:
      restrictions:
        users:
          - promise
        teams: []
        apps:
          - renovate
