# https://github.com/repository-settings/app
_extends: promise/.github

branches:
  - name: main
    protection:
      restrictions:
        apps:
          - renovate
        users:
          - promise
